MODEL:
  WEIGHTS: "data/model_final.pth"
  DEVICE: cpu
  ROI_HEADS:
    NUM_CLASSES: 6
    NMS_THRESH_TEST: 0.25
    SCORE_THRESH_TEST: 0.5
  RPN:
    NMS_THRESH: 0.6
  ANCHOR_GENERATOR:
    SIZES: [[32, 64, 128, 256, 512, 1024]]
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]
  RETINANET:
    SCORE_THRESH_TEST: 0.5
  PANOPTIC_FPN:
    COMBINE:
      INSTANCES_CONFIDENCE_THRESH: 0.5
VERSION: 2
